<?php
include(CORE_PATH.'functions/functions.php');
include(CORE_PATH.'classes/db.class.php');
include(CORE_PATH.'classes/tpl.class.php');
include(CORE_PATH.'classes/form.class.php');
include(CORE_PATH.'classes/tform.class.php');
include(CORE_PATH.'classes/files.class.php');
include(CORE_PATH.'cp/init/init.php');
include(CORE_PATH.'cp/init/init.lang.php');
?>